version: "3"
services:
  api:
    build:
      context: ./
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    container_name: api
    restart: always
    environment:
      NODE_ENV: dev
      DEBUG: nodejs-docker-express:*
    env_file:
      - .env
  redis:
    image: "redis:latest"
    container_name: cache
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
